name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # every day at midnight UTC
  workflow_dispatch:  # allow manual trigger

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Contribution Snake
        uses: Platane/snk@v3.3.0
        with:
          github_user_name: BhaveshKhaple
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push snake to output branch
        run: |
          cd dist
          git init
          git remote add origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Generated GitHub Contribution Snake"
          git branch -M main
          git push --force origin main:output
